---

- name: "Add repo key."
  apt_key:
    keyserver: "{{ dropbox_gpg_key_server }}"
    id: "{{ dropbox_gpg_key_id }}"

- name: "Add repository."
  apt_repository:
    repo: "{{ dropbox_deb_source }}"
    state: "present"
