---
- name: "Ensure HTTPS apt transport installed."
  apt:
    name: "apt-transport-https"
    state: present

- name: "Add repository."
  template:
    src: templates/dropbox.list.j2
    dest: /etc/apt/sources.list.d/dropbox.list

- name: "Add repo key."
  apt_key:
    keyserver: "{{ dropbox_gpg_key_server }}"
    id: "{{ dropbox_gpg_key_id }}"
